export default cards = [
  {
    emoji: '👩',
    title: 'Longest Hair',
    desc: 'Player with the longest hair drinks',
    type: 'Default',
  },
  {
    emoji: '🏃‍♂️',
    title: 'Catch Up!',
    desc: 'Whoever has drank the least throughout this game drinks',
    type: 'Default',
  },
  {
    emoji: '👻',
    title: 'Boo!',
    desc: 'Player with the highest Snapchat score drinks',
    type: 'Default',
  },
  {
    emoji: '💰',
    title: 'Ka-Ching!',
    desc: `Player with the least money in their wallet drinks. If you don't want to show, take 2 shots`,
    type: 'Default',
  },
  {
    emoji: '',
    title: 'Screw You In Particular',
    desc: `[Random Player] drinks`,
    type: 'Default',
  },
  {
    emoji: '📱',
    title: 'Cheap',
    desc: `Player with the cheapeast phone drinks`,
    type: 'Default',
  },
  {
    emoji: '📱',
    title: 'Rich',
    desc: `Player with the most expensive phone drinks`,
    type: 'Default',
  },
  {
    emoji: '🧛‍♂️',
    title: 'Are You A Vampire?',
    desc: `Player with the palest skin drinks`,
    type: 'Default',
  },
  {
    emoji: '🐺',
    title: 'Are You A Werewolf?',
    desc: `The hairiest player drinks`,
    type: 'Default',
  },
  {
    emoji: '💳',
    title: 'Stacked',
    desc: `Player with the most cards in their wallet drinks (credit, loyalty, ID, etc.)`,
    type: 'Default',
  },
  {
    emoji: '🛒',
    title: 'Shop-Alcoholic',
    desc: `Player who most recently bought something online drinks`,
    type: 'Default',
  },
  {
    emoji: '👧',
    title: 'Ms. Popular',
    desc: `The next player to receive a notification on their phone drinks`,
    type: 'Default',
  },
  {
    emoji: '🚗',
    title: 'I Am Speed',
    desc: `Everybody must touch the ground, last person drinks`,
    type: 'Default',
  },
  {
    emoji: '👇',
    title: 'Down It',
    desc: `[Random Player] must finish their drink!`,
    type: 'Default',
  },
  {
    emoji: '📸',
    title: 'Insta Normie',
    desc: `Player with the most Instagram followers drinks`,
    type: 'Default',
  },
  {
    emoji: '🎢',
    title: 'Slidin In',
    desc: `[Random Player] must share their last 3 direct messages or finish their drink!`,
    type: 'Default',
  },
  {
    emoji: '👑',
    title: 'Short King',
    desc: `Shortest player drinks`,
    type: 'Default',
  },
  {
    emoji: '🤲',
    title: `You're Welcome`,
    desc: `[Random Player] gets to choose another player to drink`,
    type: 'Default',
  },
  {
    emoji: '🏋',
    title: 'Plank You',
    desc: `All players must plank, first one out drinks`,
    type: 'Default',
  },
  {
    emoji: '👨',
    title: 'Shortest Hair',
    desc: 'The player with the shortest hair drinks',
    type: 'Default',
  },
  {
    emoji: '👴',
    title: 'Respect Your Elders',
    desc: 'The oldest player drinks',
    type: 'Default',
  },
  {
    emoji: '🃏',
    title: 'Wild Card',
    desc:
      '[Random Player] gets to challenge another player to a game / dare, loser drinks!',
    type: 'Default',
  },
  {
    emoji: '👶',
    title: `Aww isn't he cute?`,
    desc: 'The youngest player drinks',
    type: 'Default',
  },
  {
    emoji: '🎥',
    title: `Don't Forget To Susbcribe`,
    desc: `[Random Player] must share a screenshot of their recommended videos (YouTube, Netflix, etc.) or finishes their drink`,
    type: 'Default',
  },
  {
    emoji: '😳',
    title: `Embarassing...`,
    desc: `[Random Player] must post whatever the other players decide or finishes their drink`,
    type: 'Default',
  },
  {
    emoji: '✋',
    title: `Hands Up`,
    desc: `[Random Player] must take a drink without using their hands`,
    type: 'Default',
  },
  {
    emoji: '👽',
    title: `Conspiracy or Real?`,
    desc: `[Random Player] explains a conspiracy theory they believe in, otherwise they drink`,
    type: 'Default',
  },
  {
    emoji: '🐒',
    title: `Pull That Up Jaime`,
    desc: `Everybody names the podcasts that they listen to, whoever listens to the most drinks`,
    type: 'Default',
  },
  {
    emoji: '🦧',
    title: `Thats Crazy... Have You Tried DMT?`,
    desc: `Everybody names the podcasts that they listen to, whoever listens to the least drinks`,
    type: 'Default',
  },
  {
    emoji: '🧹',
    title: `Nice Place`,
    desc: `Whoever has the cleanest room drinks (share pictures if possible)`,
    type: 'Default',
  },
  {
    emoji: '🗑',
    title: `How Can You Live Like This?`,
    desc: `Whoever has the messiest room drinks (share pictures if possible)`,
    type: 'Default',
  },
  {
    emoji: '💅',
    title: `Girl Power`,
    desc: `Every girl drinks!`,
    type: 'Default',
  },
  {
    emoji: '👨',
    title: `Bro Time`,
    desc: `Every dude drinks!`,
    type: 'Default',
  },
  {
    emoji: '🥖',
    title: `Parlez Vous Francais?`,
    desc: `[Random Player] must attempt a French accent or finish their drink`,
    type: 'Default',
  },
  {
    emoji: '☕',
    title: `Chewsday Innit?`,
    desc: `[Random Player] must attempt a British accent or finish their drink`,
    type: 'Default',
  },
  {
    emoji: '🎭',
    title: `Funguy`,
    desc: `[Random Player] tries to make any other player laugh, if they're unsuccesful they take a drink, any player who laughs drinks`,
    type: 'Default',
  },
  {
    emoji: '👩‍⚖️',
    title: `Order in The Court!`,
    desc: `[Random Player] comes up with a rule for the rest of the game (ie. "Say cheers before every drink, if you don't, take another drink")`,
    type: 'Default',
  },
  {
    emoji: '👨‍⚖️',
    title: `Objection!`,
    desc: `[Random Player] comes up with a rule for the rest of the game (ie. "Say cheers before every drink, if you don't, take another drink")`,
    type: 'Default',
  },
];
