export default cards = [
  {
    emoji: '👩',
    title: 'Longest Hair',
    desc: 'Player with the longest hair drinks',
    type: 'Default',
  },
  {
    emoji: '🏃‍♂️',
    title: 'Catch Up!',
    desc: 'Whoever has drank the least throughout this game drinks',
    type: 'Default',
  },
  {
    emoji: '👻',
    title: 'Boo!',
    desc: 'Player with the highest Snapchat score drinks',
    type: 'Default',
  },
  {
    emoji: '💰',
    title: 'Ka-Ching!',
    desc: `Player with the least money in their wallet drinks. If you don't want to show, take 2 shots`,
    type: 'Default',
  },
  {
    emoji: '',
    title: 'Screw You In Particular',
    desc: `[Random Player] drinks`,
    type: 'Default',
  },
  {
    emoji: '📱',
    title: 'Cheap',
    desc: `Player with the cheapeast phone drinks`,
    type: 'Default',
  },
  {
    emoji: '📱',
    title: 'Rich',
    desc: `Player with the most expensive phone drinks`,
    type: 'Default',
  },
  {
    emoji: '🧛‍♂️',
    title: 'Are You A Vampire?',
    desc: `Player with the palest skin drinks`,
    type: 'Default',
  },
  {
    emoji: '🐺',
    title: 'Are You A Werewolf?',
    desc: `The hairiest player drinks`,
    type: 'Default',
  },
  {
    emoji: '💳',
    title: 'Stacked',
    desc: `Player with the most cards in their wallet drinks (credit, loyalty, ID, etc.)`,
    type: 'Default',
  },
  {
    emoji: '🛒',
    title: 'Shop-Alcoholic',
    desc: `Player who most recently bought something online drinks`,
    type: 'Default',
  },
  {
    emoji: '👧',
    title: 'Ms. Popular',
    desc: `The next player to receive a notification on their phone drinks`,
    type: 'Default',
  },
  {
    emoji: '🚗',
    title: 'I Am Speed',
    desc: `Everybody must touch the ground, last person drinks`,
    type: 'Default',
  },
  {
    emoji: '👇',
    title: 'Down It',
    desc: `[Random Player] must finish their drink!`,
    type: 'Default',
  },
  {
    emoji: '📸',
    title: 'Insta Normie',
    desc: `Player with the most Instagram followers drinks`,
    type: 'Default',
  },
  {
    emoji: '🎢',
    title: 'Slidin In',
    desc: `[Random Player] must share their last 3 direct messages or finish their drink!`,
    type: 'Default',
  },
  {
    emoji: '👑',
    title: 'Short King',
    desc: `Shortest player drinks`,
    type: 'Default',
  },
  {
    emoji: '🤲',
    title: `You're Welcome`,
    desc: `[Random Player] gets to choose another player to drink`,
    type: 'Default',
  },
  {
    emoji: '🏋',
    title: 'Plank You',
    desc: `All players must plank, first one out drinks`,
    type: 'Default',
  },
  {
    emoji: '👨',
    title: 'Shortest Hair',
    desc: 'The player with the shortest hair drinks',
    type: 'Default',
  },
  {
    emoji: '👴',
    title: 'Respect Your Elders',
    desc: 'The oldest player drinks',
    type: 'Default',
  },
  {
    emoji: '🃏',
    title: 'Wild Card',
    desc:
      '[Random Player] gets to challenge another player to a game / dare, loser drinks!',
    type: 'Default',
  },
  {
    emoji: '👶',
    title: `Aww isn't he cute?`,
    desc: 'The youngest player drinks',
    type: 'Default',
  },
  {
    emoji: '🎥',
    title: `Don't Forget To Susbcribe`,
    desc: `[Random Player] must share a screenshot of their recommended videos (YouTube, Netflix, etc.) or finishes their drink`,
    type: 'Default',
  },
  {
    emoji: '😳',
    title: `Embarassing...`,
    desc: `[Random Player] must post whatever the other players decide or finishes their drink`,
    type: 'Default',
  },
  {
    emoji: '✋',
    title: `Hands Up`,
    desc: `[Random Player] must take a drink without using their hands`,
    type: 'Default',
  },
  {
    emoji: '👽',
    title: `Conspiracy or Real?`,
    desc: `[Random Player] explains a conspiracy theory they believe in, otherwise they drink`,
    type: 'Default',
  },
  {
    emoji: '🐒',
    title: `Pull That Up Jaime`,
    desc: `Everybody names the podcasts that they listen to, whoever listens to the most drinks`,
    type: 'Default',
  },
  {
    emoji: '🦧',
    title: `Thats Crazy... Have You Tried DMT?`,
    desc: `Everybody names the podcasts that they listen to, whoever listens to the least drinks`,
    type: 'Default',
  },
  {
    emoji: '🧹',
    title: `Nice Place`,
    desc: `Whoever has the cleanest room drinks (share pictures if possible)`,
    type: 'Default',
  },
  {
    emoji: '🗑',
    title: `How Can You Live Like This?`,
    desc: `Whoever has the messiest room drinks (share pictures if possible)`,
    type: 'Default',
  },
  {
    emoji: '💅',
    title: `Girl Power`,
    desc: `Every girl drinks!`,
    type: 'Default',
  },
  {
    emoji: '👨',
    title: `Bro Time`,
    desc: `Every dude drinks!`,
    type: 'Default',
  },
  {
    emoji: '🥖',
    title: `Parlez Vous Francais?`,
    desc: `[Random Player] must attempt a French accent or finish their drink`,
    type: 'Default',
  },
  {
    emoji: '☕',
    title: `Chewsday Innit?`,
    desc: `[Random Player] must attempt a British accent or finish their drink`,
    type: 'Default',
  },
  {
    emoji: '🎭',
    title: `Funguy`,
    desc: `[Random Player] tries to make any other player laugh, if they're unsuccesful they take a drink, any player who laughs drinks`,
    type: 'Default',
  },
  {
    emoji: '👩‍⚖️',
    title: `Order in The Court!`,
    desc: `[Random Player] comes up with a rule for the rest of the game (ie. "Say cheers before every drink, if you don't, take another drink")`,
    type: 'Default',
  },
  {
    emoji: '👨‍⚖️',
    title: `Objection!`,
    desc: `[Random Player] comes up with a rule for the rest of the game (ie. "Say cheers before every drink, if you don't, take another drink")`,
    type: 'Default',
  },
  {
    emoji: '🎤',
    title: `Karaoke Night`,
    desc: `Everybody sings a song together and takes a drink afterwards`,
    type: 'Default',
  },
  {
    emoji: '🎰',
    title: `Jackpot`,
    desc: `Everybody but [Random Player] drinks`,
    type: 'Default',
  },
  {
    emoji: '🩹',
    title: `Scarred For Life`,
    desc: `[Random Player] shares a scar / injury story, otherwise they drink`,
    type: 'Default',
  },
  {
    emoji: '🚬',
    title: `Got a Light?`,
    desc: `Everybody who regularly smokes drinks`,
    type: 'Default',
  },
  {
    emoji: '👓',
    title: `4-Eyes`,
    desc: `Everybody who's wearing glasses drinks`,
    type: 'Default',
  },
  {
    emoji: '🎮',
    title: `Epic Gamer Move`,
    desc: `Whoever owns an RGB keyboard or mouse drinks`,
    type: 'Default',
  },
  {
    emoji: '🍎',
    title: `Fan Boy`,
    desc: `Whoever owns the most Apple products drinks`,
    type: 'Default',
  },
  {
    emoji: '🌏',
    title: `Well Travelled`,
    desc: `The player who has visited the most countries drinks`,
    type: 'Default',
  },
  {
    emoji: '🧭',
    title: `Survivalist`,
    desc: `Everybody must agree on which player would be the best at surviving in the wilderness, that player drinks`,
    type: 'Default',
  },
  {
    emoji: '🛏',
    title: `Sleepy Head`,
    desc: `Whichever player sleeps in the longest, on average, drinks`,
    type: 'Default',
  },
  {
    emoji: '👗',
    title: `Well Dressed`,
    desc: `Everybody must agree on which player is the most well dressed, they drink`,
    type: 'Default',
  },
  {
    emoji: '💪',
    title: `Are You Ready To Rumble?`,
    desc: `[Random Player] chooses an opponent to arm wrestle, loser drinks`,
    type: 'Default',
  },
  {
    emoji: '⚖',
    title: `Judgement Time`,
    desc: `[Random Player] comes up with a rule for the rest of the game (ie. "Say cheers before every drink, if you don't, take another drink")`,
    type: 'Default',
  },
  {
    emoji: '💡',
    title: `Inventor`,
    desc: `[Random Player] must come up with a product that they must attempt to 'sell' to the other players, if they're unsuccessful they must drink`,
    type: 'Default',
  },
  {
    emoji: '👟',
    title: `Sneakerhead`,
    desc: `The player wearing the most expensive shoes in the group drinks`,
    type: 'Default',
  },
  {
    emoji: '🐶',
    title: `Who's a Good Boy?`,
    desc: `The player with the cutest pet drinks (share pictures if possible)`,
    type: 'Default',
  },
  {
    emoji: '🚓',
    title: `Woop Woop`,
    desc: `Everybody who's ever gotten arrested drinks`,
    type: 'Default',
  },
  {
    emoji: '🌪',
    title: `Watch Out!`,
    desc: `Any player who's lived through a natural disaster drinks`,
    type: 'Default',
  },
  {
    emoji: '🚌',
    title: `Good Citizen`,
    desc: `Whichever player takes public transportation most frequently drinks`,
    type: 'Default',
  },
  {
    emoji: '🚗',
    title: `Can't be asked tbh`,
    desc: `Whichever player drives the most drinks`,
    type: 'Default',
  },
  {
    emoji: '🎌',
    title: `Domo Arigato`,
    desc: `[Random Player] must attempt a Japanese accent or finish their drink`,
    type: 'Default',
  },
  {
    emoji: '💃',
    title: `Muy Bien`,
    desc: `[Random Player] must attempt a Spanish accent or finish their drink`,
    type: 'Default',
  },
  {
    emoji: '✌',
    title: `Rock Paper Scissors`,
    desc: `[Random Player] challenges another player to a game of Rock Paper Scissors, loser drinks`,
    type: 'Default',
  },
  {
    emoji: '🧦',
    title: `Socks to Be You`,
    desc: `Whichever player has the most colorful socks drinks`,
    type: 'Default',
  },
  {
    emoji: '🔋',
    title: `1% Gang`,
    desc: `Whichever player's phone battery is the lowest drinks`,
    type: 'Default',
  },
  {
    emoji: '👆',
    title: `Karma Farming`,
    desc: `Whichever player has the most Reddit karma drinks`,
    type: 'Default',
  },
  {
    emoji: '🎷',
    title: `Saxophone Guy`,
    desc: `Whichever player knows how to play the most instruments drinks`,
    type: 'Default',
  },
  {
    emoji: '💻',
    title: `Derp`,
    desc: `Every player names a meme, everbody but the player who named the oldest meme drinks (check on knowyourmeme.com if necessary)`,
    type: 'Default',
  },
  {
    emoji: '📧',
    title: `You've Got Mail`,
    desc: `Whichever player has the most unread emails drinks`,
    type: 'Default',
  },
  {
    emoji: '🌿',
    title: `Green Thumb`,
    desc: `Whichever player has the most plants in their home drinks`,
    type: 'Default',
  },
  {
    emoji: '👃',
    title: `Nose Goes!`,
    desc: `Every player must touch their nose, last person to do so drinks`,
    type: 'Default',
  },
  {
    emoji: '💍',
    title: `Bejeweled`,
    desc: `Whichever player is wearing the most jewlery drinks`,
    type: 'Default',
  },
  {
    emoji: '💄',
    title: `True Beauty`,
    desc: `Whichever player is wearing the most makeup drinks`,
    type: 'Default',
  },
  {
    emoji: '📱',
    title: `Clutter Expert`,
    desc: `Whichever player has the most tabs open on their phone drinks`,
    type: 'Default',
  },
  {
    emoji: '🥃',
    title: `Freebie`,
    desc: `Everybody, except for the player drinking the strongest drink out of the group, drinks`,
    type: 'Default',
  },
  {
    emoji: '⌚',
    title: `Happy Hour`,
    desc: `If its after 5pm, take a drink!`,
    type: 'Default',
  },
  {
    emoji: '⛱',
    title: `Nice Tan`,
    desc: `Whichever player is the most tanned drinks`,
    type: 'Default',
  },
  {
    emoji: '🤏',
    title: `Shortest Name`,
    desc: `Whichever player has the shortest first name drinks`,
    type: 'Default',
  },
  {
    emoji: '👢',
    title: `You Know What They Say`,
    desc: `Whichever player has the largest shoe size drinks`,
    type: 'Default',
  },
  {
    emoji: '🎮',
    title: `Get a 1-Up Bro`,
    desc: `Whichever player has the most hours in a video game drinks`,
    type: 'Default',
  },
  {
    emoji: '📋',
    title: `Clippy Clippy`,
    desc: `[Random Player] must show what is currently copied to their phone or computer's clipboard, otherwise drink`,
    type: 'Default',
  },
  {
    emoji: '🤡',
    title: `Honk Honk`,
    desc: `[Random Player] describes a recent embarassing thing that happened to them, otherwise drink`,
    type: 'Default',
  },
  {
    emoji: '🕷',
    title: `Alcoholophobia`,
    desc: `Everybody shares their irrational fears, the player with the strangest fear drinks`,
    type: 'Default',
  },
  {
    emoji: '😭',
    title: `Bwah`,
    desc: `[Random Player] pretends to cry, the other players deem whether or not it was believable enough, if not, drink`,
    type: 'Default',
  },
  {
    emoji: '👄',
    title: `Red Lips`,
    desc: `Whichever player has the reddest lips drinks`,
    type: 'Default',
  },
  {
    emoji: '🤠',
    title: `Yeehaw`,
    desc: `[Random Player] must attempt a Texan accent or finish their drink`,
    type: 'Default',
  },
  {
    emoji: '🙈',
    title: `Blind`,
    desc: `[Random Player] takes a drink with their eyes closed`,
    type: 'Default',
  },
  {
    emoji: '💯',
    title: `Smartass`,
    desc: `Whichever player had the best grades in highschool drinks`,
    type: 'Default',
  },
  {
    emoji: '👇',
    title: `Dumbass`,
    desc: `Whichever player had the worst grades in highschool drinks`,
    type: 'Default',
  },
  {
    emoji: '🗺',
    title: `Mr.Worldwide`,
    desc: `Whichever player speaks (at least at a basic level) the most exotic language drinks`,
    type: 'Default',
  },
  {
    emoji: '🥗',
    title: `We Get It`,
    desc: `All the vegetarians in the group drink`,
    type: 'Default',
  },
  {
    emoji: '🍳',
    title: `Early Bird Get The Worm`,
    desc: `Whichever player gets up the earliest drinks`,
    type: 'Default',
  },
  {
    emoji: '🦉',
    title: `Night Owl`,
    desc: `Whichever player goes to sleep the latest drinks`,
    type: 'Default',
  },
  {
    emoji: '🌈',
    title: `Rainbow Lolipops`,
    desc: `Whichever player is wearing the most colorful clothing drinks`,
    type: 'Default',
  },
  {
    emoji: '🖍',
    title: `2nd Grader`,
    desc: `Whichever player has the worst handwriting drinks`,
    type: 'Default',
  },
  {
    emoji: '👖',
    title: `Wow Those Fit So Much`,
    desc: `Whichever player has the largest pockets drinks`,
    type: 'Default',
  },
  {
    emoji: '🐌',
    title: `Typist`,
    desc: `Whichever plyer types the slowest drinks`,
    type: 'Default',
  },
  {
    emoji: '🧠',
    title: `Big Brain`,
    desc: `Whichever player has the largest head drinks`,
    type: 'Default',
  },
  {
    emoji: '💊',
    title: `The Ray Kurzweil Method`,
    desc: `Whichever player takes the most supplements drinks`,
    type: 'Default',
  },
  {
    emoji: '🤖',
    title: `0010110101101`,
    desc: `[Random Player] must "do the robot" dance or drink`,
    type: 'Default',
  },
  {
    emoji: '‼',
    title: `Double Whammy`,
    desc: `[Random Player] takes two drinks together with another player`,
    type: 'Default',
  },
  {
    emoji: '🙆‍♂️',
    title: `Skyscraper`,
    desc: `Tallest player drinks`,
    type: 'Default',
  },
];
